### ISSUE TITLE
RuntimeError: cannot perform reduction function max on tensor with no elements because the operation does not have an identity

### ISSUE THREAD

**Issue by Hanawh** [feiyuhuahuo/Yolact_minimal#1]
This problem occurs when I train the model in  2 gpus and batchsize=8 , epoch = 0, iteration = 910. It seems like there is a wrong with 'match' function.   

```
each_box_max, each_box_index = overlaps.max(1)    # size [num_objects], the max IoU for each gt box
RuntimeError: cannot perform reduction function max on tensor with no elements because the operation does not have an identity
```

**Comment by Huan131** [comment]
I find the problems ! I am trying to figure out it .
it occurs because all the boxes of one image are crowd_boxes!

**Comment by feiyuhuahuo** [comment]
Sorry for replying so late. I thought github would remind me on the homepage when there's a new issue, but it didn't. Seems you solved the problem. By the way, are you training with image_size=550, there's a problem when training with other sizes, I'm trying to fix it.

**Comment by Hanawh** [comment]
I did not solve the question successfully. The problem doesn't seem to be there. I am also trying to fix it.

**Comment by imdsafi09** [comment]
i have also the same problem...if any solve this problem please help me :

best_ious, best_n = ious.max(0)
RuntimeError: cannot perform reduction function max on tensor with no elements because the operation does not have an identity

**Comment by feiyuhuahuo** [comment]
@imdsafi09  Does this case occur on a specified image? If so, maybe the related label file is not correct. Check the mistaken label.

**Comment by imdsafi09** [comment]
yah this problem occurs on certain images but every time it happen randomly

**Comment by feiyuhuahuo** [comment]
@imdsafi09 Pay attention to your box labels and the data augmentation. When training, the data augmentation is a random way. Make sure you have also dealt with the box label transformation according your augmentation method.
