### ISSUE TITLE
save the instance matching boundaries into a separate pictures

### ISSUE THREAD

**Issue by x0rzkov** [feiyuhuahuo/Yolact_minimal#10]
Hi,

Hope you are all well again :-) !

I wanted to know if we can implement an option to crop the results into separate pictures. I am talking about both; the bounding box and the instance segmentation.

Thanks in advance for your insights and inputs on the topic.

Cheers,
X

**Comment by feiyuhuahuo** [comment]
You can use `--hide_bbox` and `--hide_mask` options in terminal to control the saved images. There are several commands at the beginning of `detect.py`. Take a look.

**Comment by x0rzkov** [comment]
I mean cropping the area inside the mask and removing the background.

**Comment by feiyuhuahuo** [comment]
It can be done. A few lines of codes are needed I think. You can change the `draw_img` function by yourself.

**Comment by x0rzkov** [comment]
I tried on my local install but I do not understand how to crop the mask, if you can help me that would be wonderful.

**Comment by feiyuhuahuo** [comment]
You want to do image matting, right? I update the code. It's simpler now. 
Uncomment these four lines to get a matting result.
https://github.com/feiyuhuahuo/Yolact_minimal/blob/a680a8d1eef33490037b54e668934aea769bbb97/utils/output_utils.py#L264-L267

**Comment by x0rzkov** [comment]
It is much more background removal and keep the mask of instances detected.

**Comment by lucmichalski** [comment]
I am interested too by this functionality ! bump +1

**Comment by feiyuhuahuo** [comment]
@x0rzkov @lucmichalski  I updated the code.  Use `--cutout` in the terminal to cut out each objects.

**Comment by lucmichalski** [comment]
just awesome :-)

**Comment by x0rzkov** [comment]
@feiyuhuahuo do you have a twitter account ? I would like to DM you and ask some questions about object detection without polluting this issue ? my twitter account is https://twitter.com/x0rzkov

**Comment by feiyuhuahuo** [comment]
@x0rzkov  I don't have a  twitter account and I have no way to register one. You can email me: feiyuhuahuo@gmail.com

**Comment by x0rzkov** [comment]
Hi,

Hope you are all well !

Is it possible to save the cutout/polygon or bounding box/rectangle as a json file per image processed for labelme import ?

Cheers,
X
