### ISSUE TITLE
Valid Error! Can you tell me How to solve this question?

### ISSUE THREAD

**Issue by xuweitj** [feiyuhuahuo/Yolact_minimal#12]
Traceback (most recent call last):
  File "train.py", line 205, in <module>
    table, box_map, mask_map = compute_val_map(net.module)
  File "train.py", line 59, in compute_val_map
    table, box_row, mask_row = evaluate(yolact_net, val_dataset, during_training=True)
  File "/xw/Yolact_minimal/eval.py", line 308, in evaluate
    nms_outs = NMS(net_outs, traditional_nms)
  File "/xw/Yolact_minimal/utils/output_utils.py", line 116, in NMS
    box_decode = decode(box_p, anchors)  # [19248, 4]
  File "/xw/Yolact_minimal/utils/box_utils.py", line 173, in decode
    boxes = torch.cat((priors[:, :2] + box_p[:, :2] * variances[0] * priors[:, 2:],
RuntimeError: The size of tensor a (19248) must match the size of tensor b (1212624) at non-singleton dimension 0

**Comment by feiyuhuahuo** [comment]
Are you training a custom dataset?  Have you modified the code?

**Comment by xuweitj** [comment]
yes, I am training a custom dataset. I modified the code according to https://blog.csdn.net/qq_39056987/article/details/106722609.



At 2020-09-01 13:34:11, "Slark" <notifications@github.com> wrote:

Are you training a custom dataset? Have you modified the code?

**Comment by xuweitj** [comment]
Only the valid part in train.py gets error like above. If I remove the valid part code, it's OK.

**Comment by feiyuhuahuo** [comment]
Check the shape of the `box_p` and `anchors` here in NMS, they should both be (19248, 4). If not, you might have changed the train image size?

![image](https://user-images.githubusercontent.com/32631344/91810705-f0409000-ec60-11ea-85c1-8cda45013022.png)
