### ISSUE TITLE
train my dataset

### ISSUE THREAD

**Issue by GUUUUG** [feiyuhuahuo/Yolact_minimal#14]
Hello, when I train my own data set (512×512), the graphics card occupancy rate is 0% (but the graphics card memory occupies about 10%), and there is no intermediate process, such as loss function display, why is this?

**Comment by GUUUUG** [comment]
> 您好，当我训练自己的数据集（512×512）时，图形卡的占用率为0％（但是图形卡的内存占用约为10％），并且没有中间过程，例如丢失功能显示，为什么？这个？

No response when in the picture
![QQ图片20200929155306](https://user-images.githubusercontent.com/54826762/94529622-88d02d00-026c-11eb-847e-713df35e721d.png)

**Comment by GUUUUG** [comment]
No response when the following text appears

loading annotations into memory...
Done (t=0.00s)
creating index...
index created!

**Comment by feiyuhuahuo** [comment]
Check your dataset path, I guess the program did not find your data.

**Comment by GUUUUG** [comment]
> 检查您的数据集路径，我猜程序找不到您的数据。

![QQ图片20200929165828](https://user-images.githubusercontent.com/54826762/94536165-06983680-0275-11eb-9fab-6468c703c14a.png)
训练数据存放的地址是对的呀

**Comment by GUUUUG** [comment]
您好，我在训练时发现貌似没用调用COCODetection这个类，其中红框内是否有调用？
Hello, I found that it seems useless to call the COCODetection class during training. Is there a call in the red box?





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "feiyuhuahuo/Yolact_minimal"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月29日(星期二) 下午4:30
收件人:&nbsp;"feiyuhuahuo/Yolact_minimal"<Yolact_minimal@noreply.github.com&gt;;
抄送:&nbsp;"王广杰"<953704875@QQ.COM&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [feiyuhuahuo/Yolact_minimal] train my dataset (#14)





 
Check your dataset path, I guess the program did not find your data.

**Comment by feiyuhuahuo** [comment]
COCODetection已经初始化，不然不会出现COCO的加载json的提示信息，打印下datum看，有没有内容
![image](https://user-images.githubusercontent.com/32631344/94575794-352f0500-02a7-11eb-98c9-db73a46cc63b.png)

**Comment by GUUUUG** [comment]
> COCODetection已经初始化，不然不会出现COCO的加载json的提示信息，打印下datum看，有没有内容
> ![图片](https://user-images.githubusercontent.com/32631344/94575794-352f0500-02a7-11eb-98c9-db73a46cc63b.png)

![J(WP~V_E}I EWY)%TGC CRX](https://user-images.githubusercontent.com/54826762/94758135-f7c59700-03ce-11eb-85c2-6ff1c6ce2642.png)
您好，我修改好annotations.json后，程序可以运行，但是mask ap为何为0？
