### ISSUE TITLE
Detect only single class

### ISSUE THREAD

**Issue by Nerdyvedi** [feiyuhuahuo/Yolact_minimal#16]
Hi, I would like to detect only one class. Not able to understand where should I make the change? Thank you

**Comment by feiyuhuahuo** [comment]
Modify `CUSTOM_CLASSES` in `config.py`. For one class, like `('dog', )`, for two or more classes, like `('dog', 'cat')`.
You also need to prepare a coco-style json for training.

**Comment by Nerdyvedi** [comment]
@feiyuhuahuo I need to detect one class only for inference. It gives error while loading the weights if I remove every other class.Thanks

**Comment by feiyuhuahuo** [comment]
For only inference, there's nothing you need to do. Just let the model detect your images. If the model detected other classes in your image, that just means the model detected wrongly. For better results, you'd better train the model on your one class dataset.

**Comment by Nerdyvedi** [comment]
@feiyuhuahuo So, Is there any way to not detect any classes with the pretrained model?

**Comment by feiyuhuahuo** [comment]
You can not show other class objects when drawing the detected pictures. But this doesn't mean the model did not detect them, they are just  shielded.

**Comment by Nerdyvedi** [comment]
@feiyuhuahuo . How do I not show it?

**Comment by feiyuhuahuo** [comment]
Add the following two lines in utils.output_utils:
![图片](https://user-images.githubusercontent.com/32631344/100560998-87fe5a80-32f2-11eb-8ca2-14e643eaf3ac.png)

**Comment by Nerdyvedi** [comment]
@feiyuhuahuo Thank you so much. What if I want to combine 2 classes? For example, Person and cell phone?

**Comment by feiyuhuahuo** [comment]
`keep = (class_ids==0) + (class_ids==67)`
