### ISSUE TITLE
How to deal with different Aspect Ratios ?

### ISSUE THREAD

**Issue by Ruwen14** [feiyuhuahuo/Yolact_minimal#18]
Hello everyone,

I want to detect cars in aerial images from a low altitude(drones) with YOLACT. So far I've gathered data that has yet to be labeled. 
The thing is, the original images vary in aspect ratios - 5472x3648 (3:2) and 3840x2160(16:9) respectively.

![Bild1](https://user-images.githubusercontent.com/73891246/99371157-d2c5ae80-28be-11eb-8494-50b63f274596.png)

When resizing the images to the input size of YOLACT (550x550) the cars looked either squished or very elongated. I'm concerned that YOLACT won't be able to learn the masks of the cars properly as they look squished or elongated depending on their pose. 
Therefore, my questions:
  1.) Are aspect ratios besides 1:1 supported? Or even multiple aspect ratios like in my case?
  2.) If not, should I just let them resize to 550x550 and hope for the best?
  3.) OR, Should I crop them to 1:1 and lose information or use padding with black bars?

Besides that, I'm uncertain about cut off cars. Should I label them or only those who are fully present in the frame?

A lot of questions I know, but I would be very happy about your help

Regards,
Ruwen

**Comment by feiyuhuahuo** [comment]
If you're detecting only class and the images do not differ obviously. Then that's  an easy dataset. For easy dataset, resizing the images directly to 550*550 is OK. You don't need to do other image processing. The model can both recognize the normal cars and squeezed cars.
For labeling, I advise that if a certain part of one car occurs in the image, then you label it. If only the edge of a car occurs, then ignore it. This also depends on your detection requirements.
Another suggestion, seems your images are large ones, I suggest you resize them to a small resolution first, e.g. width/4, height/4 of the original images. If you directly pass the large images to the model, it'll take more time for data pre-processing and slow down the training.

**Comment by Ruwen14** [comment]
Hi @feiyuhuahuo thanks for the quick reply,

of course the images will be resized beforehand anyway. I'm just concerned that the Network will be confused when learning the masks, because the cars look either squished when horizontal or elongated when vertical based on the resizing on 550x550. But you dont think that will be a problem ?

**Comment by feiyuhuahuo** [comment]
Unless the cars are squeezed close to a line, e.g. length:width =7:1, 8:1, 9:1 ... Or it has no influence. That's because your dataset is an easy one, the model has the ability to learn both the normal cars and the squeezed cars. There are also some other object detection algorithms using such a resizing way. CNNs do not watch like human eyes.

**Comment by Ruwen14** [comment]
Okay sounds good. 
Thanks a lot! 

Have a nice weekend
