### ISSUE TITLE
YOLACT

### ISSUE THREAD

**Issue by zhangbaoj** [feiyuhuahuo/Yolact_minimal#2]
Do you know how to draw the loss curve of YOLACT?

**Comment by feiyuhuahuo** [comment]
Sorry for replying so late. I thought github would remind me on the homepage when there's a new issue, but it didn't. 
To draw the loss, you can use tensorboardX.
A brief code:
![image](https://user-images.githubusercontent.com/32631344/67063210-7adae680-f198-11e9-8954-e2760258ce95.png)
Then in the terminal: tensorboard --logdir log

**Comment by zhangbaoj** [comment]
Thank you very much for your help.
