### ISSUE TITLE
Issues with cropping

### ISSUE THREAD

**Issue by Nerdyvedi** [feiyuhuahuo/Yolact_minimal#23]
Hi,
Do you think it is possible to improve the performance of [crop function](https://github.com/feiyuhuahuo/Yolact_minimal/blob/d61c99d1a8492b7dafec4cbc2d93cd02b27c0260/utils/box_utils.py#L164) ?

It slows down the model and introduces lag.
Another issue I found was, the bounding box of one subject is cutting out other subject's mask as well.

**Comment by feiyuhuahuo** [comment]
I'll see if I can improve this if I have time.

**Comment by Nerdyvedi** [comment]
Okay, Thanks. Do you have any ideas now, I can implement it and create a PR

**Comment by feiyuhuahuo** [comment]
I have no idea. Crop operation is already implemented by matrix multiply, which I think is hard to improve with pure Python code. And for cutting out other objects' masks, it doesn't matter. Because the learning target is a complete object mask, other masks pixels should be suppressed.

**Comment by Nerdyvedi** [comment]
Actually, I am using Crop operation during inference. If I add the no_crop option, there are blotches of noise outside the box, And on adding the crop operation, the mask of one subject is cutting out other's mask.

**Comment by feiyuhuahuo** [comment]
That maybe the model did not learn quite well. But this is also my assumption. I'll check it detaily if I have time. Besides, are you noticing this thing on COCO or on your custom dataset?

**Comment by Nerdyvedi** [comment]
Model trained on COCO dataset, I am only detecting person class, But blotches are present outside the box.
