### ISSUE TITLE
Torch to ONNX conversion going wrong

### ISSUE THREAD

**Issue by Darshcg** [feiyuhuahuo/Yolact_minimal#26]
Hi @feiyuhuahuo,

I am converting yoloact model (trained on my custom dataset) to ONNX, the conversion is completing successfully, but in the ONNX model one of the node is not getting connected to the graph.
I have attached the picture of the graph below.

Having said that, the pytorch model Inference is working fine, but not sure why one of the node is not getting connected to the graph in the onnx model.

Can you please assist me to solve this error? Would be a great help from yourside.

Also, I tried with torch version 1.6, 1.7 but still the same.

I am attaching the screenshot of the graph below:
![Screenshot from 2021-05-18 12-17-13](https://user-images.githubusercontent.com/48723743/118605142-91617d80-b7d3-11eb-9ac2-c0bc1df1980c.png)

Thanks,
Darshan

**Comment by Darshcg** [comment]
Looking forward to your reply.

Thanks,
Darshan

**Comment by feiyuhuahuo** [comment]
I'll check it detaily if I have time. You can consult this issue first. (https://github.com/feiyuhuahuo/Yolact_minimal/issues/24#issuecomment-817652104)

**Comment by Darshcg** [comment]
I referred to the same, I have changed the version and checked but still no Luck.

Thanks,
Darshan
