### ISSUE TITLE
RuntimeError: weights/best_30.5_res101_coco_392000.pth is a zip archive (did you mean to use torch.jit.load()?)

### ISSUE THREAD

**Issue by kazuki-can** [feiyuhuahuo/Yolact_minimal#27]
Hi, I'm new here.
I found this model really fantastic.
Now, I am trying to use this to cut out the background of image.
And I got the error above.
How can I sort it out?

**Comment by feiyuhuahuo** [comment]
How did you get this error?  If you try to load this pth file with `torch.load()`, it should be OK, and you can get a Ordered dict.

**Comment by kazuki-can** [comment]
I sorted it out by upgrading pytorch version.
But I got a new error saying 
`Traceback (most recent call last):
  File "detect.py", line 57, in <module>
    assert ds > 0, 'No .jpg images found.'
AssertionError: No .jpg images found.`
How can I sort this problem out ?
Thanks

**Comment by feiyuhuahuo** [comment]
That means there are no jpg image in the `images` folder, thus the program interrupted.

**Comment by kazuki-can** [comment]
Thank you for helping me.
Is it possible to use png image file to this model?
Thanks

**Comment by feiyuhuahuo** [comment]
https://github.com/feiyuhuahuo/Yolact_minimal/blob/4c3e50dde56c8a83c411c6d5d4f657b497356f3f/utils/coco.py#L55
Change the `jpg` to `png`, you can detect png images.

**Comment by kazuki-can** [comment]
Thank you so much.
It worked!

**Comment by kazuki-can** [comment]
I have one more question.
I want to use this model  for my own images, so I wrote the command like below
`python detect.py --weight=weights/best_30.5_res101_coco_392000.pth --image=D:\img00027.png`
But I got a error saying 
`Traceback (most recent call last):
  File "detect.py", line 58, in <module>
    assert ds > 0, 'No .jpg images found.'
AssertionError: No .jpg images found.`
Does the original code correspond to any images or do I need to change a bit ?

**Comment by feiyuhuahuo** [comment]
Just pass the folder path to `--image`, you can put your images in that folder.

**Comment by kazuki-can** [comment]
I set the path to the image folder.
But I got a newe error.
`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\333\anaconda3\envs\yolact\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\333\anaconda3\envs\yolact\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\333\anaconda3\envs\yolact\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\333\anaconda3\envs\yolact\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\333\anaconda3\envs\yolact\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\333\anaconda3\envs\yolact\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\333\anaconda3\envs\yolact\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\333\Documents\Yolact_minimal\detect.py", line 62, in <module>
    for i, (img, img_origin, img_name) in enumerate(data_loader):
  File "C:\Users\333\anaconda3\envs\yolact\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\333\anaconda3\envs\yolact\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
    w.start()
  File "C:\Users\333\anaconda3\envs\yolact\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\333\anaconda3\envs\yolact\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\333\anaconda3\envs\yolact\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\333\anaconda3\envs\yolact\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\333\anaconda3\envs\yolact\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\333\anaconda3\envs\yolact\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "C:\Users\333\anaconda3\envs\yolact\lib\site-packages\torch\utils\data\dataloader.py", line 761, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "C:\Users\333\anaconda3\envs\yolact\lib\queue.py", line 172, in get
    raise Empty
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "detect.py", line 62, in <module>
    for i, (img, img_origin, img_name) in enumerate(data_loader):
  File "C:\Users\333\anaconda3\envs\yolact\lib\site-packages\torch\utils\data\dataloader.py", line 345, in __next__
    data = self._next_data()
  File "C:\Users\333\anaconda3\envs\yolact\lib\site-packages\torch\utils\data\dataloader.py", line 841, in _next_data
    idx, data = self._get_data()
  File "C:\Users\333\anaconda3\envs\yolact\lib\site-packages\torch\utils\data\dataloader.py", line 798, in _get_data
    success, data = self._try_get_data()
  File "C:\Users\333\anaconda3\envs\yolact\lib\site-packages\torch\utils\data\dataloader.py", line 774, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 39132, 34332, 26760, 24508) exited unexpectedly`
How can I fix this error?

**Comment by Sandeep418** [comment]
> I set the path to the image folder.
> But I got a newe error.
> `Traceback (most recent call last):
> File "", line 1, in
> File "C:\Users\333\anaconda3\envs\yolact\lib\multiprocessing\spawn.py", line 105, in spawn_main
> exitcode = _main(fd)
> File "C:\Users\333\anaconda3\envs\yolact\lib\multiprocessing\spawn.py", line 114, in _main
> prepare(preparation_data)
> File "C:\Users\333\anaconda3\envs\yolact\lib\multiprocessing\spawn.py", line 225, in prepare
> _fixup_main_from_path(data['init_main_from_path'])
> File "C:\Users\333\anaconda3\envs\yolact\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
> run_name="**mp_main**")
> File "C:\Users\333\anaconda3\envs\yolact\lib\runpy.py", line 263, in run_path
> pkg_name=pkg_name, script_name=fname)
> File "C:\Users\333\anaconda3\envs\yolact\lib\runpy.py", line 96, in _run_module_code
> mod_name, mod_spec, pkg_name, script_name)
> File "C:\Users\333\anaconda3\envs\yolact\lib\runpy.py", line 85, in _run_code
> exec(code, run_globals)
> File "C:\Users\333\Documents\Yolact_minimal\detect.py", line 62, in
> for i, (img, img_origin, img_name) in enumerate(data_loader):
> File "C:\Users\333\anaconda3\envs\yolact\lib\site-packages\torch\utils\data\dataloader.py", line 279, in **iter**
> return _MultiProcessingDataLoaderIter(self)
> File "C:\Users\333\anaconda3\envs\yolact\lib\site-packages\torch\utils\data\dataloader.py", line 719, in **init**
> w.start()
> File "C:\Users\333\anaconda3\envs\yolact\lib\multiprocessing\process.py", line 105, in start
> self._popen = self._Popen(self)
> File "C:\Users\333\anaconda3\envs\yolact\lib\multiprocessing\context.py", line 223, in _Popen
> return _default_context.get_context().Process._Popen(process_obj)
> File "C:\Users\333\anaconda3\envs\yolact\lib\multiprocessing\context.py", line 322, in _Popen
> return Popen(process_obj)
> File "C:\Users\333\anaconda3\envs\yolact\lib\multiprocessing\popen_spawn_win32.py", line 33, in **init**
> prep_data = spawn.get_preparation_data(process_obj._name)
> File "C:\Users\333\anaconda3\envs\yolact\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
> _check_not_importing_main()
> File "C:\Users\333\anaconda3\envs\yolact\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
> is not going to be frozen to produce an executable.''')
> RuntimeError:
> An attempt has been made to start a new process before the
> current process has finished its bootstrapping phase.
> 
> ```
>     This probably means that you are not using fork to start your
>     child processes and you have forgotten to use the proper idiom
>     in the main module:
> 
>         if __name__ == '__main__':
>             freeze_support()
>             ...
> 
>     The "freeze_support()" line can be omitted if the program
>     is not going to be frozen to produce an executable.
> ```
> 
> Traceback (most recent call last):
> File "C:\Users\333\anaconda3\envs\yolact\lib\site-packages\torch\utils\data\dataloader.py", line 761, in _try_get_data
> data = self._data_queue.get(timeout=timeout)
> File "C:\Users\333\anaconda3\envs\yolact\lib\queue.py", line 172, in get
> raise Empty
> queue.Empty
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "detect.py", line 62, in
> for i, (img, img_origin, img_name) in enumerate(data_loader):
> File "C:\Users\333\anaconda3\envs\yolact\lib\site-packages\torch\utils\data\dataloader.py", line 345, in **next**
> data = self._next_data()
> File "C:\Users\333\anaconda3\envs\yolact\lib\site-packages\torch\utils\data\dataloader.py", line 841, in _next_data
> idx, data = self._get_data()
> File "C:\Users\333\anaconda3\envs\yolact\lib\site-packages\torch\utils\data\dataloader.py", line 798, in _get_data
> success, data = self._try_get_data()
> File "C:\Users\333\anaconda3\envs\yolact\lib\site-packages\torch\utils\data\dataloader.py", line 774, in _try_get_data
> raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
> RuntimeError: DataLoader worker (pid(s) 39132, 34332, 26760, 24508) exited unexpectedly`
> How can I fix this error?

give num_workers=0
data_loader = data.DataLoader(dataset, 1, num_workers=0, shuffle=False,
                                      pin_memory=True, collate_fn=detect_collate)

**Comment by kazuki-can** [comment]
It worked for me.
I ran the model with this command below
`python detect.py --weight=weights/best_30.5_res101_coco_392000.pth --image=ROOT_IMG_FOLDER --cutout`
Thanks a lot.

**Comment by Byronnar** [comment]
> It worked for me.
> I ran the model with this command below
> `python detect.py --weight=weights/best_30.5_res101_coco_392000.pth --image=ROOT_IMG_FOLDER --cutout`
> Thanks a lot.

could tell where can I download the model best_30.5_res101_coco_392000.pth? Thankyou!

**Comment by feiyuhuahuo** [comment]
In the master branch. @Byronnar
