### ISSUE TITLE
can;t cutout some pictures

### ISSUE THREAD

**Issue by kazuki-can** [feiyuhuahuo/Yolact_minimal#28]
Hi, I have one more question.
I wanted to segment the pictures of a person with cutout,but I got an error below.
`NUM_DETECTED : 1
Traceback (most recent call last):
  File "detect.py", line 82, in <module>
    img_numpy = draw_img2(ids_p, class_p, boxes_p, masks_p, img_origin, cfg, img_name=img_name,count=i)
  File "C:\Users\###\Documents\Yolact_minimal\utils\output_utils.py", line 392, in draw_img2
    cv2.imwrite(f'results/images/img{str(count+1).zfill(5)}_{str(i)}.png', img_matting)
cv2.error: OpenCV(4.5.2) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-1bq9o88m\opencv\modules\imgcodecs\src\loadsave.cpp:721: error: (-215:Assertion failed) !_img.empty() in function 'cv::imwrite'`
It seems like img_matting is empty even though num_detected shows 1.
Why does this happen?
Thanks.

**Comment by feiyuhuahuo** [comment]
Could you e-mail me your test image: `feiyuhuahuo@gmail.com`?
And what's your command you ran?

**Comment by kazuki-can** [comment]
Okay
Thank yo somuch.

**Comment by feiyuhuahuo** [comment]
```
      if cfg.cutout:
          img_h, img_w, _ = img_origin.shape
          for i in range(num_detected):
              one_obj = np.tile(mask_p[i], (3, 1, 1)).transpose((1, 2, 0))
              one_obj = one_obj * img_origin
              new_mask = mask_p[i] == 0
              new_mask = np.tile(new_mask * 255, (3, 1, 1)).transpose((1, 2, 0))
              # If the predicted boxes are out of image range, img_matting would be empty, so do clip.
              box_p[:, [0, 2]] = np.clip(box_p[:, [0, 2]], a_min=0, a_max=img_w)
              box_p[:, [1, 3]] = np.clip(box_p[:, [1, 3]], a_min=0, a_max=img_h)
              x1, y1, x2, y2 = box_p[i, :]
              img_matting = (one_obj + new_mask)[y1:y2, x1:x2, :]
              cv2.imwrite(f'results/images/{img_name}_{i}.jpg', img_matting)
```
It's OK now.
Modify the `draw_img` function in `output_utils.py`.
The predicted boxes are out of the image range, this leads img_matting to be empty. So doing clip can solve this problem.

**Comment by kazuki-can** [comment]
It worked for me.
Thank you for helping me a lot.
