### ISSUE TITLE
AttributeError: 'PyxImporter' object has no attribute 'find_spec'

### ISSUE THREAD

**Issue by qingqinghu1026** [feiyuhuahuo/Yolact_minimal#3]
when I use this command(python3 detect.py --trained_model=yolact_base_54_800000.pth --video ./../../video/test2_2s.mkv) to detect a video, blow errors will be occured. Pleased tell me how to slove it.
![2019-11-21 15-47-42屏幕截图](https://user-images.githubusercontent.com/38452234/69317612-474b1a80-0c76-11ea-87e8-26c72162d964.png)

**Comment by feiyuhuahuo** [comment]
Line 13 in `output_utils.py` is used for traditional_nms. If you don't need traditional_nms, you can directly comment that line and the related code for traditional_nms.
Or try to reinstall Cython, I'm not sure. Because `pyximport`  comes from Cython.

**Comment by qingqinghu1026** [comment]
Thanks for your reply.
