### ISSUE TITLE
multi classes cutout

### ISSUE THREAD

**Issue by kazuki-can** [feiyuhuahuo/Yolact_minimal#30]
Hi, thanks for the past.
I want to do another task that segment multi classes in a picture and save a picture including all of them.
For example, when you can segment a person and a handbag in a picture, I want you to save the pictures of the person and a handbag.
Thank you.

**Comment by feiyuhuahuo** [comment]
Which kind of picture do you want, all the objetcs being segmented by differtent colors with the white background?

**Comment by kazuki-can** [comment]
May I email you with the pictures?

**Comment by feiyuhuahuo** [comment]
You can just describe how the segmented pictures would be like, I'll see what I can do.

**Comment by kazuki-can** [comment]
I want the segmented pictures to have a person and a backpack even when I use cutout.
Now when I use cutout, there will be two pictures of each objects if YOLACT can segment multi objects.
But as long as a person has handbag or something, I want the segmented picture to be one picture of the person and the handbag.
Thank you.

**Comment by kazuki-can** [comment]
Like, if the picture of the person has a handbag inside, I don't want it to save a person and a handbag separately.

**Comment by feiyuhuahuo** [comment]
The code still has some bugs for visualization. I'll take some time to do some test and push an update.

**Comment by feiyuhuahuo** [comment]
check the latest update, it's OK now.

**Comment by kazuki-can** [comment]
Somehow, it still gives the same result like before.
I've changed the code here
`    if not cfg.hide_mask:
        masks_semantic = mask_p * (ids_p[:, None, None] + 1)  # expand ids_p' shape for broadcasting
        # The color of the overlap area is different because of the '%' operation.
        masks_semantic = masks_semantic.astype('int').sum(axis=0) % (cfg.num_classes - 1)
        color_masks = COLORS[masks_semantic].astype('uint8')
        img_fused = cv2.addWeighted(color_masks, 0.4, img_origin, 0.6, gamma=0)

        if cfg.cutout:
            total_obj = (masks_semantic != 0)[:, :, None].repeat(3, 2)
            total_obj = total_obj * img_origin
            new_mask = ((masks_semantic == 0) * 255)[:, :, None].repeat(3, 2)
            img_matting = (total_obj + new_mask).astype('uint8')
            cv2.imwrite(f'results/images/{img_name}_total_obj.jpg', img_matting)

            for i in range(num_detected):
                one_obj = (mask_p[i])[:, :, None].repeat(3, 2)
                one_obj = one_obj * img_origin
                new_mask = ((mask_p[i] == 0) * 255)[:, :, None].repeat(3, 2)
                x1, y1, x2, y2 = box_p[i, :]
                img_matting = (one_obj + new_mask)[y1:y2, x1:x2, :]
                cv2.imwrite(f'results/images/{img_name}_{i}.jpg', img_matting)`
And here 
`parser.add_argument('--weight', type=str, default='weights/best_30.5_res101_coco_392000.pth', help='The eval model.')`

**Comment by feiyuhuahuo** [comment]
![444 jpg_total_obj](https://user-images.githubusercontent.com/32631344/122713639-9618c600-d298-11eb-860e-54c5d64c7fe7.jpg)
Is this the result you want?

**Comment by kazuki-can** [comment]
That is almost what I wanted.
But I think there is another picture of his leg.
Can you put it in the picture above?

**Comment by feiyuhuahuo** [comment]
![image](https://user-images.githubusercontent.com/32631344/122719857-59050180-d2a1-11eb-9bc1-76061bfcc976.png)
His legs were not detected. To get better result, you should finetune the model on your own dataset.

**Comment by kazuki-can** [comment]
Does that mean if his legs can be detected, the cutout picutre would be like what I said before?

**Comment by feiyuhuahuo** [comment]
yes, you can detect some other images to know about the segment result.

**Comment by kazuki-can** [comment]
Thank you so much.
I do appreciate for your work for me recently.

**Comment by feiyuhuahuo** [comment]
We don't know which item belong to which person from the model result. You need take care of the detected objects by your own to realize it.

**Comment by kazuki-can** [comment]
Okay, thank you for helping me a lot.

**Comment by kazuki-can** [comment]
I changed the code like you changed, but it does not save any pictures.

**Comment by kazuki-can** [comment]
I showed every single segmented picture, but all of them were just gray
