### ISSUE TITLE
hi,it make me conflused about the lr with swin_tiny

### ISSUE THREAD

**Issue by WYQ-Github** [feiyuhuahuo/Yolact_minimal#33]
in configs the lr is 0.00005*(train_bs/8),could you tell me the default valve 8 means what.

 is it right i set the value 2 if i have two gpus

**Comment by feiyuhuahuo** [comment]
The original lr is 0.0001 for train_bs=16 in the paper, so  it should be 0.00005 for train_bs=8. You just need to specify the total training bs on your two GPUs to --train_bs, the lr will be adjust automatically.

**Comment by feiyuhuahuo** [comment]
In the original yolact project, the default bs is 8, so I kept it here and adjust the lr linearly.

**Comment by WYQ-Github** [comment]
> In the original yolact project, the default bs is 8, so I kept it here and adjust the lr linearly.
i got it. you are so sweet. respect thx ：）

**Comment by WYQ-Github** [comment]
Hi there is a mistake when I was training
```
 step: 14500 | lr: 1.25e-04 | l_class: 5.062 | l_box: 4.992 | l_mask: 5.110 | l_semantic: 0.352 | t_t: 0.330 | t_d: 0.090 | t_fl: 0.080 | t_b: 0.133 | t_u: 0.027 | ETA: 20 days, 18:04:22
No valid object in image: 393221. Use a repeated image in this batch.
Traceback (most recent call last):
  File "train.py", line 105, in <module>
    for images, targets, masks in data_loader:
  File "/home/aibc/anaconda3/envs/jin/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/aibc/anaconda3/envs/jin/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/aibc/anaconda3/envs/jin/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/media/aibc/YuQing/Program/yolcat/Yolact_minimal-dev/utils/coco.py", line 21, in train_collate
    valid_batch.append(valid_batch[i])
IndexError: list index out of range
```
The mistake tell that the list valid_batch is NULL? Is there a broken image in my data(coco2017)?
The train2017 has 118287 images, is it right (the bs value) % 118287 == 0? 
How can I solve this problem?

**Comment by feiyuhuahuo** [comment]
What is your batch size? Maybe your batch size is too small, so it happened to get a totally invalid batch.

**Comment by WYQ-Github** [comment]
> What is your batch size? Maybe your batch size is too small, so it happened to get a totally invalid batch.

I set the bs is 3. what is about 8?

**Comment by feiyuhuahuo** [comment]
Yes，8 is ok. Do not use batch size smaller than 4.
