### ISSUE TITLE
AttributeError: 'Yolact' object has no attribute 'backbone'

### ISSUE THREAD

**Issue by Harry-KIT** [feiyuhuahuo/Yolact_minimal#35]
any help appreciated !

**Comment by feiyuhuahuo** [comment]
Which command do you run with? Do you run the project in PyCharm or in the terminal?

**Comment by Harry-KIT** [comment]
I run it in VScode terminal

**Comment by feiyuhuahuo** [comment]
Please paste the detailed error message here, I don't know where you triggered this error.

**Comment by Harry-KIT** [comment]
/home/gayrat/anaconda3/envs/Yolact_minimal/lib/python3.7/site-packages/torch/distributed/launch.py:164: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  "The module torch.distributed.launch is deprecated "
The module torch.distributed.launch is deprecated and going to be removed in future.Migrate to torch.distributed.run
WARNING:torch.distributed.run:--use_env is deprecated and will be removed in future releases.
 Please read local_rank from `os.environ('LOCAL_RANK')` instead.
INFO:torch.distributed.launcher.api:Starting elastic_operator with launch configs:
  entrypoint       : train.py
  min_nodes        : 1
  max_nodes        : 1
  nproc_per_node   : 1
  run_id           : none
  rdzv_backend     : static
  rdzv_endpoint    : 127.0.0.1:32066
  rdzv_configs     : {'rank': 0, 'timeout': 900}
  max_restarts     : 3
  monitor_interval : 5
  log_dir          : None
  metrics_cfg      : {}

INFO:torch.distributed.elastic.agent.server.local_elastic_agent:log directory set to: /tmp/torchelastic_s1rhsp8m/none_uik1andq
INFO:torch.distributed.elastic.agent.server.api:[default] starting workers for entrypoint: python
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous'ing worker group
/home/gayrat/anaconda3/envs/Yolact_minimal/lib/python3.7/site-packages/torch/distributed/elastic/utils/store.py:53: FutureWarning: This is an experimental API and will be changed in future.
  "This is an experimental API and will be changed in future.", FutureWarning
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous complete for workers. Result:
  restart_count=0
  master_addr=127.0.0.1
  master_port=32066
  group_rank=0
  group_world_size=1
  local_ranks=[0]
  role_ranks=[0]
  global_ranks=[0]
  role_world_sizes=[1]
  global_world_sizes=[1]

INFO:torch.distributed.elastic.agent.server.api:[default] Starting worker group
INFO:torch.distributed.elastic.multiprocessing:Setting worker0 reply file to: /tmp/torchelastic_s1rhsp8m/none_uik1andq/attempt_0/0/error.json

------------------------------res101_custom------------------------------
mode: train
cuda: True
gpu_id: 0
img_size: 544
class_names: polyp
num_classes: 6
scales: [24, 48, 96, 192, 384]
aspect_ratios: [1, 0.5, 2]
weight: weights/resnet50-19c8e357.pth
train_imgs: polyps_dataset/
train_ann: polyps_dataset/custom_ann.json
train_bs: 4
bs_per_gpu: 4
val_interval: 4000
bs_factor: 0.5
lr: 0.0005
warmup_init: 5e-05
warmup_until: 100
lr_steps: (0, 1200, 1600, 2000)
pos_iou_thre: 0.5
neg_iou_thre: 0.4
conf_alpha: 1
bbox_alpha: 1.5
mask_alpha: 6.125
semantic_alpha: 1
masks_to_train: 100
val_imgs: 
val_ann: 
val_bs: 1
val_num: -1
coco_api: False
traditional_nms: False
nms_score_thre: 0.05
nms_iou_thre: 0.5
top_k: 200
max_detections: 100

Traceback (most recent call last):
  File "train.py", line 55, in <module>
    net.backbone.init_backbone(cfg.weight)
  File "/home/gayrat/anaconda3/envs/Yolact_minimal/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1131, in __getattr__
    type(self).__name__, name))
AttributeError: 'Yolact' object has no attribute 'backbone'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 100112) of binary: /home/gayrat/anaconda3/envs/Yolact_minimal/bin/python
ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed
INFO:torch.distributed.elastic.agent.server.api:[default] Worker group FAILED. 3/3 attempts left; will restart worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Stopping worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous'ing worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous complete for workers. Result:
  restart_count=1
  master_addr=127.0.0.1
  master_port=32066
  group_rank=0
  group_world_size=1
  local_ranks=[0]
  role_ranks=[0]
  global_ranks=[0]
  role_world_sizes=[1]
  global_world_sizes=[1]

INFO:torch.distributed.elastic.agent.server.api:[default] Starting worker group
INFO:torch.distributed.elastic.multiprocessing:Setting worker0 reply file to: /tmp/torchelastic_s1rhsp8m/none_uik1andq/attempt_1/0/error.json

**Comment by feiyuhuahuo** [comment]
Seems you are using TorchElastic to train the moel. Can you run successfully with the original `torch.distributed.launch` ?

**Comment by Harry-KIT** [comment]
Thank you! done
