### ISSUE TITLE
No module named 'cython_nms'

### ISSUE THREAD

**Issue by tkone2018** [feiyuhuahuo/Yolact_minimal#36]
你好，感谢你的开源，我运行代码的时候，出现这个问题，
 from cython_nms import nms as cnms
ModuleNotFoundError: No module named 'cython_nms'，请问是版本问题吗 有什么解决方案吗 谢谢

**Comment by tkone2018** [comment]
搞定了

**Comment by yums24** [comment]
你好，我也遇到这个问题了，请问你是怎么解决的？

**Comment by lovedreamms** [comment]
我现在理解到错误出现的原因是这个模块是pdx需要编译为pyd，才可以使用，要下载一个vs,然后运行，但我出现了一些编译错误还没有解决
![image](https://github.com/feiyuhuahuo/Yolact_minimal/assets/122292012/b678bd6d-5611-4b33-b09c-66ea07cdbea1)
