### ISSUE TITLE
RuntimeError: No rendezvous handler for env://

### ISSUE THREAD

**Issue by Masaya-38** [feiyuhuahuo/Yolact_minimal#38]
Hi. 
I appreciate your work!
I was trying to train my custom dataset, but The following error has occurred.

Traceback (most recent call last):
  File "train.py", line 44, in <module>
    cfg = get_config(args, mode='train')
  File "C:\Users\user\models\yolact\config.py", line 218, in get_config
    dist.init_process_group(backend='nccl', init_method='env://')
  File "C:\Users\user\anaconda3\envs\yolact\lib\site-packages\torch\distributed\distributed_c10d.py", line 421, in init_process_group
    init_method, rank, world_size, timeout=timeout
  File "C:\Users\user\anaconda3\envs\yolact\lib\site-packages\torch\distributed\rendezvous.py", line 82, in rendezvous
    raise RuntimeError("No rendezvous handler for {}://".format(result.scheme))
RuntimeError: No rendezvous handler for env://
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\envs\yolact\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\user\anaconda3\envs\yolact\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\anaconda3\envs\yolact\lib\site-packages\torch\distributed\launch.py", line 260, in <module>
    main()
  File "C:\Users\user\anaconda3\envs\yolact\lib\site-packages\torch\distributed\launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\user\\anaconda3\\envs\\yolact\\python.exe', '-u', 'train.py', '--local_rank=0', '--cfg=res101_custom']' returned non-zero exit status 1.

OS : Windows10
pytorch : 1.7.0
CUDA : 11.0
The inference is working fine.
How do I solve this problem?

**Comment by feiyuhuahuo** [comment]
The code support DDP on ubuntu but not on Windows. I don't know how to implement DDP on win10.

**Comment by Masaya-38** [comment]
Thank you for your reply.
I have tried to implement Linux, but still have not been able to get it to work with the GPU driver.
So I tried a few things to get the training working on windows, and it worked when I changed the following parts.

**config.py / line 228**
before : dist.init_process_group(backend='nccl', init_method='env://')
after : dist.init_process_group(backend='gloo', init_method='file:///tmp/somefile', rank=0, world_size=1)

**train.py / line78,79**
before : #data_loader = data.DataLoader(dataset, cfg.bs_per_gpu, num_workers=0, shuffle=False,collate_fn=train_collate, pin_memory=True)
after : data_loader = data.DataLoader(dataset, cfg.bs_per_gpu, num_workers=0, shuffle=False,collate_fn=train_collate, pin_memory=True)

I trained 4000 steps on the image, but the training took about 2 hours and the inference only showed the bbox.
These are the two main changes I made. Also, I did not change output_utils/draw_img.
Did this problem happen because using DDP on win10 as you mentioned?

**Comment by Masaya-38** [comment]
Here's the image detected.
![85](https://user-images.githubusercontent.com/61003618/128820340-e16c40c3-c84d-47e6-9e55-152beb75affe.jpg)

custom_dataset : 180 images
custom_classes : trffaic cone , 
I used labelme to annotate.

**Comment by feiyuhuahuo** [comment]
How many GPUs did you use to train? This problem should has nothing to do with DDP or OS. You may check if the annotated mask label be input to the model correctly and check if there's any output predicted mask.

**Comment by Masaya-38** [comment]
I'm sorry for the late reply.

I'm using one GPU (RTX 3080 Notebooks) .
I reimplemented it in Linux so that I don't have to consider DDP or OS issues.
But as you said, it didn't seem to have anything to do with this problem, and it didn't solve it.

The values of l_mask, etc. are output during training
![Screenshot from 2021-09-24 13-17-34](https://user-images.githubusercontent.com/61003618/134618796-96514380-2917-497b-96f1-7f296c204483.png)
.
