### ISSUE TITLE
how to train myself data？

### ISSUE THREAD

**Issue by qingqinghu1026** [feiyuhuahuo/Yolact_minimal#4]
I annotated my dataset with lamebe, which is to generate a JSON file for each picture, but in the code, "train_images": "path_to train_images", "train_info": "path_to train_annotation", which should be a JSON file generated by all pictures. Please ask how to do this?Can you help me?

**Comment by feiyuhuahuo** [comment]
You mean labelme? I'm not sure whether the json file created by labelme suits with this project. The format should be same with the COCO json file. I'll try to support training custom data as soon as possible. The json file should be pass to "path_to train_annotation" anyway.

**Comment by qingqinghu1026** [comment]
sorry, it's labelme. Looking forward to your answer.

**Comment by feiyuhuahuo** [comment]
I support training custom data now, check it in the README.md
