### ISSUE TITLE
When eval, There is a mistake in after_nms.

### ISSUE THREAD

**Issue by WYQ-Github** [feiyuhuahuo/Yolact_minimal#41]
pytorch1.8.1,python=3.8,bs=8,opencv_python4.5.1.48
``` 
Traceback (most recent call last):
  File "train.py", line 167, in <module>
    table, box_row, mask_row = evaluate(net.module, cfg, step)
  File "/Aistation010806/Yolactv1/Yolact_minimal-dev/eval.py", line 52, in evaluate
    ids_p, class_p, boxes_p, masks_p = after_nms(ids_p, class_p, box_p, coef_p, proto_p, img_h, img_w)
  File "/Aistation010806/Yolactv1/Yolact_minimal-dev/utils/output_utils.py", line 261, in after_nms
    masks = F.interpolate(masks.unsqueeze(0), (ori_size, ori_size), mode='bilinear', align_corners=False).squeeze(0)
  File "/opt/conda/envs/dual_learning/lib/python3.8/site-packages/torch/nn/functional.py", line 3554, in interpolate
    return torch._C._nn.upsample_bilinear2d(input, output_size, align_corners, scale_factors)
RuntimeError: Non-empty 4D data tensor expected but got a tensor with sizes [1, 0, 160, 160]
```
Could you tell me how can I solve this mistake. ; )
thx ; )

**Comment by feiyuhuahuo** [comment]
Can you show `masks` and `box_p` just before you get this error? That's a strange mistake. I can't figure out where is wrong now.

**Comment by WYQ-Github** [comment]
box_p: (1,18525,4)
masks in after_nms. I print this line's output ```masks = torch.sigmoid(torch.matmul(proto_p, coef_p.t()))``` The output is masks:(136,136,0)

**Comment by feiyuhuahuo** [comment]
Did you modify the after_nms() function? You can paste it here.

**Comment by WYQ-Github** [comment]
The mistake what I made is that I changed The fast_nms in your project. I use raw-fast_nms, the project works now. 
Thank you very much

**Comment by WYQ-Github** [comment]
Hi,I did not modify the after_nms() function. I just modified the calculation method of IOU. But it does not work.
Forgive me that I didn't tell you about that at the beginning.
Thank you very much:)
