### ISSUE TITLE
Does this project will update yolact++ model ? I'm looking forward to it 

### ISSUE THREAD

**Issue by Nathansong** [feiyuhuahuo/Yolact_minimal#44]

**Comment by feiyuhuahuo** [comment]
I will try to add more tricks into this project to improve its performance， not limited to yolact++ tricks. But I can't give a schedule. I don't have too much time on it.

**Comment by Nathansong** [comment]
OK，I hope this project can add the fast mask re-scoring network, Thanks in advance .
