### ISSUE TITLE
Is the order of the keys important in the custom_ann.json file??.

### ISSUE THREAD

**Issue by saik2121** [feiyuhuahuo/Yolact_minimal#45]
I am getting no annotation in this image error.??

**Comment by feiyuhuahuo** [comment]
Key order doesn't matter, you can check why you get the error in __getitem__ function in coco.py.

**Comment by saik2121** [comment]
The error is that there is no annotation for this image. But i have provided the annotation in the custom_ann.json file. Im a little confused as to what to do.??

**Comment by feiyuhuahuo** [comment]
![image](https://user-images.githubusercontent.com/32631344/133707634-12c9aaff-6d32-471f-8241-e7696d16381a.png)

Check target in `__getitem__` function in coco.py.

**Comment by saik2121** [comment]
Hey, I checked those things out. The problem is that my iscrowd values are one and hence the target list is empty. What could be the workaround

**Comment by feiyuhuahuo** [comment]
Get all the elements in `target`.
```
            target = self.coco.loadAnns(ann_ids)
            target = [aa for aa in target]
```
