### ISSUE TITLE
About Validation and Validation Dataset

### ISSUE THREAD

**Issue by Darshvino** [feiyuhuahuo/Yolact_minimal#49]
Hi @feiyuhuahuo,

I just wanted to know where actually the Validation is happening on the Validation Dataset? 
By the way, Do we have to give the Validation Dataset separately?

Thanks

**Comment by feiyuhuahuo** [comment]
Validation runs at a specific interval during training, you can set it by --val_interval. You can also set the validation dataset the same as the training dataset. That depends on you.
