### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Darshvino** [feiyuhuahuo/Yolact_minimal#50]
Hi @feiyuhuahuo,

Thanks for your great work.

I am training the Yolact_minimal on the custom Dataset. During the training I am facing the issue as: IndexError: list index out of range

I am attaching the clear error trace below.
 

```
 File "train.py", line 102, in <module>
    for images, targets, masks in data_loader:
  File "/anaconda/envs/py38_default/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/anaconda/envs/py38_default/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/anaconda/envs/py38_default/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/anaconda/envs/py38_default/lib/python3.8/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 3.
Original Traceback (most recent call last):
  File "/anaconda/envs/py38_default/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/anaconda/envs/py38_default/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/anaconda/envs/py38_default/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/media/sladmin/6bb2b407-f222-4e9d-bdcb-a8062f6be6ee/darshan/Yolact_minimal/utils/coco.py", line 334, in __getitem__
    rles = maskUtils.frPyObjects(segm, height, width)
  File "pycocotools/_mask.pyx", line 292, in pycocotools._mask.frPyObjects
IndexError: list index out of range
```

Can you please help me to resolve the issue? Would help me a lot

Thanks and Regards

**Comment by Darshvino** [comment]
Hi @feiyuhuahuo,

Looking forward to your reply.

Thanks and regards

**Comment by feiyuhuahuo** [comment]
You can check if the format of your annotation json matches with the format of custom_ann.json in custom_dataset folder.

**Comment by Darshvino** [comment]
Hi @feiyuhuahuo,

Thank you for your response.

I have modified the Dataloader part. I am attaching the modified script below:

https://drive.google.com/file/d/1umfqC22RDfsEiSRWwdFL6LRBpKmRDSAX/view?usp=sharing

And this is the Sample Annotation file I am using for training: 
https://drive.google.com/file/d/1sVAuemywozOnGx6xon9IO92i8GujZ4eU/view?usp=sharing

Actually, I have kept 10000 images for Training (with BS=8 on GPU). After completing some steps(approx 100-120), it is throwing the above error.

Thanks and Regards

**Comment by Darshvino** [comment]
Hi @feiyuhuahuo,

Really looking forward to your reply. Just because we had taken the GPU Instance in GCP, and facing the issue with the Dataloader since 3 days. It would be of great help if you can help me to resolve this issue.

Thanks much!

**Comment by feiyuhuahuo** [comment]
1. Check if len(self.img_files) == 10000.
2. Use try... except... to print the json path when get error, check the error json file. According to your error traceback, I guess there's a wrong annotation in some json files.

**Comment by Darshvino** [comment]
Hi @feiyuhuahuo,

Thanks a lot for your kind reply.

As you mentioned, some json file were causing an issue. I am attaching the one such json file below:
https://drive.google.com/file/d/1JBrH5WHHCg71Fj0B_GmnmqW6ViEkre4k/view?usp=sharing

But I really don't know the reason.

Can you please help to understand the why I am getting the error, by seeing the above json file, so that I will rectify the issue.

Looking forward to your reply.

Thanks a lot!

**Comment by feiyuhuahuo** [comment]
```
import json
import pdb
import numpy as np
from pycocotools import mask as maskUtils

with open('56.json', 'rb') as f:
    data = json.load(f)

for aa in data:
    bbox = aa['bbox']

    if bbox[0] < 0 or bbox[1] < 0 or bbox[2] < 4 or bbox[3] < 4:
        continue

    x1y1x2y2_box = np.array([bbox[0], bbox[1], bbox[0] + bbox[2], bbox[1] + bbox[3]])
    category = aa['category_id']

    segm = aa["segmentation"]

    rles = maskUtils.frPyObjects(segm, 500, 500)
    rle = maskUtils.merge(rles)
    m = maskUtils.decode(rle)
    print(category, m.shape, m.max(), m.min())
```
I use the above code to read your json file and did not get error. Do you get error when reading the json file separately? 
And I found strange things in the annotation.
![image](https://user-images.githubusercontent.com/32631344/134288589-73f70fff-850e-4b3c-954a-977e44ba9c4d.png)
Why the max element is 0? 0 means background, the foreground annotation should always be 1.

**Comment by feiyuhuahuo** [comment]
What is your image height and width?

**Comment by Darshvino** [comment]
Hi @feiyuhuahuo,

Thank you a lot for your continuous support.

As asked the image Height= 512, Width=616

Thank you again!

**Comment by Darshvino** [comment]
And for a reference, I am attaching the corresponding image for the annotation file I have attached above:

**Image**: https://drive.google.com/file/d/1vj7Uk5haEhTj_K4foA4PG1LFSGlarQeI/view?usp=sharing

**Annotation file**: https://drive.google.com/file/d/1JBrH5WHHCg71Fj0B_GmnmqW6ViEkre4k/view?usp=sharing

Thank you

**Comment by feiyuhuahuo** [comment]
Is this the json file where you get error? I read it separately and did not get any error. Can you read it separately successfully? If so, what's your pycocotools version? and how you install it?

**Comment by Darshvino** [comment]
Heyy @feiyuhuahuo,

Thank you a lot for your responses and for your time. You are very kind.

It was an issue with the Segmentation values being empty in some json files.

Btw everything is working now!

Just sharing a screenshot of the training.

![image](https://user-images.githubusercontent.com/41161376/134428838-cdc084b4-4e62-4395-b9c9-a9179a4ee5fe.png)

Just wanted to confirm if everything is right in the above screenshot?

I am training on 10000 images, with BS=4, Val_interval=2000, Val images= 400

Thanks and Regards

**Comment by feiyuhuahuo** [comment]
Seems nothing unnormal. A larger batch size is better.

**Comment by Darshvino** [comment]
ohh Thank you a Lot @feiyuhuahuo.

**Comment by Darshvino** [comment]
Hi @feiyuhuahuo,

With respect to validation, it is taking whole 10000 images for Validation.

![image](https://user-images.githubusercontent.com/41161376/134463521-72dc6b09-b46b-40c8-b66c-44c01f1259e2.png)
But  I want to change it take to take only 500 images for Validation. Where do we need to change that?

Thanks

**Comment by Darshvino** [comment]
2.) And this is the Validation results:

![image](https://user-images.githubusercontent.com/41161376/134468417-afd7f665-ebfa-4ddf-b738-bf3826226637.png)
Not Sure why the MAPs are Zero?

Whether everything is fine?

Looking forward to your reply.

**Comment by feiyuhuahuo** [comment]
Modify __len__() function in coco.py to make --val_num=500 available.
```
    def __len__(self):
        if self.mode == 'train':
            return len(self.ids)
        elif self.mode == 'val':
            return len(self.ids) if self.cfg.val_num == -1 else min(self.cfg.val_num, len(self.ids))
        elif self.mode == 'detect':
            return len(self.image_path)
```
1k iterations are far from enough. With batch size 4, you even didn't go through one epoch.

**Comment by Darshvino** [comment]
Thank you for your quick reply @feiyuhuahuo.

1.) Btw how many iterations do I need to keep? And how do I need to calculate it(let's say for example 10000 Images).

2.) And why the MAP values are Zero? whether something is going wrong or it is usual?

Thanks and Regards

**Comment by Darshvino** [comment]
I kept it for 40000 Steps and still the MAP values are zero.

![image](https://user-images.githubusercontent.com/41161376/134538594-c3e2f5ad-4b91-4bbc-b603-8392bb8da5c4.png)

Is everything is right here or something needs to be modified or it is usuall?

**Comment by feiyuhuahuo** [comment]
I can't tell if this is right. But the loss looks right, it's the same as training on COCO.

**Comment by Darshvino** [comment]
Thank you very much @feiyuhuahuo. Everything is working smoothly.
