### ISSUE TITLE
TypeError: __init__() missing 4 required positional arguments: 'casting', 'from_', 'to', and 'i'

### ISSUE THREAD

**Issue by Darshvino** [feiyuhuahuo/Yolact_minimal#51]
Hi @feiyuhuahuo,

I am trying to train a Yolact_minimal on total of 3750000 images on 2 A100 GPUs.

During the start of the training I am getting as error as below:

![image](https://user-images.githubusercontent.com/41161376/134589519-32335e87-69c3-48e6-ace0-3e2d8fd6464b.png)

What is the reason of this error? Is this a version issue or a Dataloader issue?

Here are some details of training: 
-> Total images: 3750000
-> command used to run:  **python3 -m torch.distributed.launch --nproc_per_node=2 --master_port=$((RANDOM)) train.py --train_bs=16**
-> torch installation command used:  pip3 install torch==1.8.1+cu111 torchvision==0.9.1+cu111 -f https://download.pytorch.org/whl/torch_stable.html
-> Val_interval: 10000
-> lr_steps=(0, 800000)
-> Classes = 37 classes.

I have Modified a Dataloader a bit to train on my custom Dataset.
Here is the Customisation of the Dataloader: https://drive.google.com/file/d/1umfqC22RDfsEiSRWwdFL6LRBpKmRDSAX/view

Can you please help me to resolve this issue?

But the same worked on K80 GPU. 

Looking forward to your reply.

Thanks and Regards

**Comment by feiyuhuahuo** [comment]
You mean no error when training on two K80 GPUs?

**Comment by Darshvino** [comment]
No, one K80 GPU.

And I kept  **python3 -m torch.distributed.launch --nproc_per_node=1 --master_port=$((RANDOM)) train.py --train_bs=16** on A100 Machine, again it was the same error.

Is it some version issue or some other?

**Comment by Darshvino** [comment]
Thanks a lot @feiyuhuahuo for your help.

I am able to successfully train!
