### ISSUE TITLE
How can I test on coco-test2017?

### ISSUE THREAD

**Issue by yuqing526** [feiyuhuahuo/Yolact_minimal#53]
Hi, Thanks for your work.
I have tested on val2017 already.
Could you tell me how to test on test2017? 
Thanks a lot:)

**Comment by feiyuhuahuo** [comment]
You can use detect.py and add  a part of evaluation code to get the json file.
The evaluation code can consult to:https://github.com/feiyuhuahuo/Yolact_minimal/blob/dc8335abfd1187c43e53ce579a26f0513dc1dfce/eval.py#L86-L104
