### ISSUE TITLE
Changing FPN 

### ISSUE THREAD

**Issue by abhigoku10** [feiyuhuahuo/Yolact_minimal#55]
@feiyuhuahuo  thanks for sharing the code base, do u think we can increase the performance of yolact by using BiFPN , PAnetFPN, Panoptic FPN in the network ??

**Comment by feiyuhuahuo** [comment]
Yes， these components can help to improve yolact's performance. But I think the key factors are focused on the detector of yolact. Especially on the sample select strategy, training loss. I also want to improve its performance and I plan to consult to YoloX(https://github.com/Megvii-BaseDetection/YOLOX). I like its sample select strategy and simple training loss. But I do not have much time on it. May be you can take a look at it.
