### ISSUE TITLE
train problem

### ISSUE THREAD

**Issue by Harry-zzh** [feiyuhuahuo/Yolact_minimal#57]
Hi, when I use the command
`python -m torch.distributed.launch --nproc_per_node=1 --master_port=$((RANDOM)) train.py --cfg=res50_custom` to train the model, the page is stuck for a long time like this:
![image](https://user-images.githubusercontent.com/54358503/147379738-aa29b99c-57f1-418c-a7ae-fcfb38d097c9.png)

I wonder why it happens.

Looking forward to your reply！

**Comment by feiyuhuahuo** [comment]
check if your data path is right. This problem usually because the train script can not find your data.

**Comment by Harry-zzh** [comment]
I think my data path is right, because I simply use the custom dataset that you have provided.
![image](https://user-images.githubusercontent.com/54358503/147380766-e42552f9-584f-411e-9f8f-cadbc899bcf2.png)

**Comment by feiyuhuahuo** [comment]
Please use COCO dataset to run, custom dataset is used for annotation demonstration and I don't know whether the script can run successfully with it.

**Comment by Harry-zzh** [comment]
OK, thank you.
