### ISSUE TITLE
Long train time

### ISSUE THREAD

**Issue by Harry-zzh** [feiyuhuahuo/Yolact_minimal#58]
Hi, I use my own custom dataset to train the model with resnet50 backbone, but the training seems to take a long time.

![image](https://user-images.githubusercontent.com/54358503/147516734-479eda64-0942-421c-9334-60328a21e7bd.png)

The ETA even reachs 99 days.

There are only 1000 images in my dataset. I wonder why it happens.

Looking forward to your reply!

**Comment by feiyuhuahuo** [comment]
't_d' means the time used for  data preprocess, which is extremely unnormal. Usually it is in range of 0.04~0.08. How many num_workers do you use? Do you run the program on Win10?

**Comment by Harry-zzh** [comment]
Oh, I find that I set num_workers to 0 accidentally, now I will set it to 8. I run the program on Linux:

![image](https://user-images.githubusercontent.com/54358503/147519051-2f62b9b8-64ba-4f11-94c5-e57cefa2e95f.png)

But is it normal to take a few minutes to load the data? My training batch size is 4. The page is still stuck until now:

![image](https://user-images.githubusercontent.com/54358503/147519386-3b2b68b4-0623-47c9-a85f-b8479ae5af4c.png)

**Comment by feiyuhuahuo** [comment]
https://github.com/feiyuhuahuo/Yolact_minimal/blob/d920c0563f54746426a006cd3af83ff3bae293cc/utils/coco.py#L54-L55
Please check here if  the script can get your data.

**Comment by Harry-zzh** [comment]
Finally I found the reason. I forgot to modify the CUSTOM_CLASSES. Now the training process is normal:

![image](https://user-images.githubusercontent.com/54358503/147533731-49ac8cb3-9cf5-456f-9832-abdecee653ad.png)

Thank you very much.
