### ISSUE TITLE
关于在装甲板检测中的相关问题？

### ISSUE THREAD

**Issue by nowhereman1999** [feiyuhuahuo/Yolact_minimal#59]
@feiyuhuahuo 大佬，你好，就是我是一名大二学生，然后是在中北大学的robomaster战队里负责用神经网络识别装甲板实现自动瞄准，不过就是之前我用yolo系列训练出来的模型最后实际测试时得到的bbox和装甲板的轮廓并不能很好的拟合，导致后续使用pnp进行姿态解算时会有较大误差，所以我想通过yolact直接分割出装甲板然后用opencv来提取坐标，不过后续就是我想使用c++下的openvino来部署加速，我看您在repo里提供了pythonxia的trt加速，我之前也实现过yolov5使用c++下的trt的加速，参考的tensorrtx这个repo，不过由于在nano上帧率太低，故不得不放弃使用trt加速的想法，只能等下学期经费到了以后看能否买上nx，目前队里就还有一个nuc10以及一个mindvision的工业相机，相机的api我已经封装好了，可以像videocapture那样来读取相机，所以我之后想尝试一下yolact来实现装甲板的检测，大佬，能够给一些建议以及openvino部署方案的可行性评估吗？望大佬解惑

**Comment by feiyuhuahuo** [comment]
yolact 在RTX2080上大概有30fps，还是有一定的计算量，要提速只能用更小的骨架网络。openvino部署我也没什么经验

**Comment by nowhereman1999** [comment]
> yolact 在RTX2080上大概有30fps，还是有一定的计算量，要提速只能用更小的骨架网络。openvino部署我也没什么经验

好吧，多谢大佬的回复，所以按您的意思是只能将backbone替换为mobilrnet或shufflenet这类更轻量的网络才能实现速度的进一步提升是吗？

**Comment by feiyuhuahuo** [comment]
要提速可以替换更轻量的backbone，然后FPN, 检测头那里可以适当降低一点通道数。要不然就只能做量化，用半精度或int8推理。

**Comment by nowhereman1999** [comment]
> 要提速可以替换更轻量的backbone，然后FPN, 检测头那里可以适当降低一点通道数。要不然就只能做量化，用半精度或int8推理。

FP16还是可以接受，但是INT8感觉掉点太多，误检可能比较严重，我看yolactedge就用mobilenet替换了backbone，在agx上能到33fps左右，但是目前我更关注yolact分割的话定位装甲板四个角点是否更加准确，因为我现在也在yolov5-face基础上改四点模型，有学校已经改出来了，效果如下![3_demo(1).jpg](https://user-images.githubusercontent.com/53631206/147652237-60cf3eee-ad53-45ab-a019-0e73e2df3a9d.jpg)，所以大佬有什么看法呢？

**Comment by feiyuhuahuo** [comment]
不太清楚你用yolo的检测精度是怎样。能不能检测准确和你的训练数据，检测场景，目标复杂程度都有关系。在准确性上，分割应该不会比目标检测有优势，能分割准的，一般都能检测准。不过我之前也用过yolov5，也出现过检测不准的情况，不知道是不是这个项目本身的问题。

**Comment by nowhereman1999** [comment]
> 不太清楚你用yolo的检测精度是怎样。能不能检测准确和你的训练数据，检测场景，目标复杂程度都有关系。在准确性上，分割应该不会比目标检测有优势，能分割准的，一般都能检测准。不过我之前也用过yolov5，也出现过检测不准的情况，不知道是不是这个项目本身的问题。

用yolov5的话感觉recall比较低，当然应该是由于我数据集的问题，当时就用一个类的装甲板数据集训练的，因为我觉得yolact的数据集在标注时就是通过关键点标注的，而且装甲板是一个长方形，四个角点就可以拟合轮廓，所以我觉得这和我现在在yolov5-face的基础上改的四点模型有异曲同工之妙，所以我打算用yolact试试，主要是不知道之后用openvino部署方不方便，目前比较担心这个：-（

**Comment by feiyuhuahuo** [comment]
你试试把，我也不好判断
