### ISSUE TITLE
请求原作者帮助

### ISSUE THREAD

**Issue by mcmingchang** [feiyuhuahuo/Yolact_minimal#60]
你好，感谢你的工作，我把你这边实力分割的代码尝试迁移到yolox上，代码没报错但是推理没有结果，有空可以看看吗。目前项目已添加了关键点检测和全景分割版本，还差实例分割没有进展https://github.com/mcmingchang/yolox_keypoint_segment/tree/main

**Comment by feiyuhuahuo** [comment]
推理没有结果是什么意思，是指可以顺利训练，但是训练后预测没有分割的结果吗

**Comment by mcmingchang** [comment]
谢谢作者的关注，现在已经可以跑出来结果了，然后我试着去改变mask标签和训练的方式，发现10分类的话第一个分类不能显示，其他都可以。换新的mask标签的话训练更快且支持yolox的所有增强

**Comment by mcmingchang** [comment]
代码已完成，谢谢

**Comment by mcmingchang** [comment]
有个事情想请教你。mask_p = seg_proto[bb] @ pos_coef.t() 这个计算完后会变成nan，就是训练久了肯定会Nan，但是不变成Nan的话模型输出的结果很棒，不知道作者可以提供点解决思路么

**Comment by mcmingchang** [comment]
crop_mask = (masks_left * masks_right * masks_up * masks_down) * 1 这样能在fp16下避免变成nan
