### ISSUE TITLE
convert models isssues: pytorch2onnx , onnx2coreml

### ISSUE THREAD

**Issue by dzyjjpy** [feiyuhuahuo/Yolact_minimal#8]
Hi @feiyuhuahuo thanks for your work.  Have you tried to convert models to use it on cell phone?
I met some trouble when converting. could you pls share if you have experience?

**Comment by dzyjjpy** [comment]
https://github.com/onnx/onnx-coreml/issues/347#issuecomment-598096919
https://github.com/onnx/onnx-coreml/issues/347#issuecomment-598106173

**Comment by feiyuhuahuo** [comment]
I have no idea. I once tried to convert yolact to ONNX, but I failed. I did not pay much effort on it.

**Comment by dzyjjpy** [comment]
@feiyuhuahuo okay, thanks for your quick update
