### ISSUE TITLE
Rest web service / Can't call numpy() on Variable that requires grad. Use var.detach().numpy() instead.

### ISSUE THREAD

**Issue by x0rzkov** [feiyuhuahuo/Yolact_minimal#9]
Hi,

Hope you are all well !

I forked your repository, https://github.com/x0rzkov/Yolact_minimal/, and made some additions like adding a dockerfile for cpu and gpu, but one of my new feature is not working.

I wanted to create a web service for testing results from postman, and I have an error like below:
```sh
Traceback (most recent call last):
  File "./server.py", line 131, in process
    img_numpy = draw_img(results, img_origin, args)
  File "/yolact/utils/output_utils.py", line 257, in draw_img
    class_ids, classes, boxes = [x[:args.visual_top_k].cpu().numpy() for x in results[:3]]
  File "/yolact/utils/output_utils.py", line 257, in <listcomp>
    class_ids, classes, boxes = [x[:args.visual_top_k].cpu().numpy() for x in results[:3]]
RuntimeError: Can't call numpy() on Variable that requires grad. Use var.detach().numpy() instead.
```

To run the websever in local
```sh
pip3 install requests werkzeug flask Image
python3 server.py
```

To run the webserver with docker
```sh
docker network create web
docker-compose up yolact
```

Any idea what is the problem ?
Do you want me to make a pull request for the docker files ?

Cheers,
X

**Comment by feiyuhuahuo** [comment]
Have you removed this: `with torch.no_grad():` at the beginning of `detect.py` ? If so, some tensors would need gradients by default. In detecting mode, no gradient is needed.
